#!/bin/sh

commit_regex='^(feat|fix|docs|style|refactor|perf|test|chore|ci|build|temp)(\(.+\))?: .{1,50}'
error_msg="Aborting commit. Your commit message does not follow Conventional Commits format."

if ! grep -qE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
