name: Build and Versioning

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: Install dependencies
        env:
          CI: true
        run: npm ci

      - name: Run build
        if: success()
        run: npm run build
